spring:
  application:
    name: customer-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer_db
    username: customer
    password: customer
    hikari:
      connection-timeout: 1000
      validation-timeout: 1000
      max-lifetime: 1800000
      leak-detection-threshold: 5
      maximum-pool-size: 3
  jpa:
    show-sql: false
    open-in-view: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non-contextual-creation: true
        batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true
        default_schema: #@todo adicionar schema

server:
  port: 8080

flyway:
  datasources:
    default:
      locations: classpath:databasemigrations